### ISSUE TITLE
class Meta of Models

### ISSUE THREAD

**Issue by ostcar** [machinalis/mypy-django#10]
I ran into a problem with mypy on the [Meta](https://docs.djangoproject.com/en/1.11/topics/db/models/#meta-options) classes of Django models. The mypy issue tracker redirected my to this place.

Do you have an answer for this question? https://github.com/python/mypy/issues/3855

**Comment by lordi** [comment]
Is there a workaround for this? An ignore annotation for Meta itsself does not help.

**Comment by ostcar** [comment]
I don't know of any workaround. Maybe you can ping the issue in the mypy repo
